### ISSUE TITLE
Skip empty item lists

### ISSUE THREAD

**Issue by corneliusweig** [corneliusweig/ketall#21]
**Describe the bug**
When running `ketall --since 1s -o yaml`, most resource types are empty, but they are printed as
```
apiVersion: v1
items:
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
- items: null
  metadata: {}
kind: List
metadata: {}
```

**Expected behavior**
Empty lists should be skipped altogether.
